/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controller.CompraController;
import controller.VentaController;
import model.DatabaseConnector;
import controller.UsuarioController;

import javax.swing.*;
import java.sql.SQLException;   

/**
 *
 * @author alberto
 */
public class DashboardJF extends javax.swing.JFrame {
 private int idUsuario; // ID del usuario

    // Constructor que recibe el idUsuario al iniciar sesión
    public DashboardJF(int idUsuario) {
        this.idUsuario = idUsuario; // Guarda el idUsuario en el DashboardJF
        initComponents();
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comprabtn = new javax.swing.JButton();
        ventabtn = new javax.swing.JButton();
        reportebtn = new javax.swing.JButton();
        edperfilbtn = new javax.swing.JButton();
        cerrarSesionbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DASHBOARD");

        comprabtn.setText("REGISTRAR COMPRA");
        comprabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprabtnActionPerformed(evt);
            }
        });

        ventabtn.setText("REGISTRAR VENTA");
        ventabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventabtnActionPerformed(evt);
            }
        });

        reportebtn.setText("GENERAR REPORTE");

        edperfilbtn.setText("EDITAR PERFIL");

        cerrarSesionbtn.setText("CERRAR");
        cerrarSesionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cerrarSesionbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edperfilbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reportebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ventabtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comprabtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comprabtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ventabtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edperfilbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrarSesionbtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        // Método para abrir RCompra
      private void abrirRegistroCompra() {
        DatabaseConnector dbConnector = new DatabaseConnector();
        CompraController compraController = new CompraController(dbConnector);
        RCompra rCompra = new RCompra(idUsuario, compraController); // Pasa el controlador y el idUsuario
        rCompra.setVisible(true);
      }
      
      // Método para abrir RVenta
    private void abrirRegistroVenta() {
        DatabaseConnector dbConnector = new DatabaseConnector();
        VentaController ventaController = new VentaController(dbConnector);
        RVenta rVenta = new RVenta(idUsuario, ventaController); // Pasa el controlador y el idUsuario
        rVenta.setVisible(true);
}

    
    private void comprabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprabtnActionPerformed
        // Crear una instancia de RCompra y hacerla visible
         abrirRegistroCompra(); // Llama al método que abre RCompra
    }//GEN-LAST:event_comprabtnActionPerformed

    private void cerrarSesionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionbtnActionPerformed
        // TODO add your handling code here:
         try {
        // Crear una instancia del controlador de usuario
        DatabaseConnector dbConnector = new DatabaseConnector();
        UsuarioController usuarioController = new UsuarioController(dbConnector);

        // Cerrar la conexión del controlador
        usuarioController.cerrarConexion();

        // Mostrar mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Sesión cerrada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Abrir la ventana Main
        Main main = new Main();
        main.setVisible(true);

        // Cerrar el Dashboard actual
        dispose();

    } catch (Exception e) {
        // Manejo de cualquier error inesperado
        JOptionPane.showMessageDialog(this, "Error al cerrar la sesión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_cerrarSesionbtnActionPerformed

    private void ventabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventabtnActionPerformed
        // TODO add your handling code here:
           // Crear una instancia de RVenta y hacerla visible
        abrirRegistroVenta(); // Llama al método que abre RVenta
    }//GEN-LAST:event_ventabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesionbtn;
    private javax.swing.JButton comprabtn;
    private javax.swing.JButton edperfilbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reportebtn;
    private javax.swing.JButton ventabtn;
    // End of variables declaration//GEN-END:variables
}
